import urllib.request
import xml.etree.ElementTree as ET
import json
import os
import time
import random

BASE = os.path.expanduser('~/Projects/provenance/test_suite')

# ============ 1. ACADEMIC PAPERS (20) from arXiv ============
print('=== Fetching 20 academic abstracts from arXiv ===')
academic_queries = [
    'http://export.arxiv.org/api/query?search_query=cat:cs.AI&start=0&max_results=5&sortBy=submittedDate&sortOrder=ascending',
    'http://export.arxiv.org/api/query?search_query=cat:physics.gen-ph&start=0&max_results=5&sortBy=submittedDate&sortOrder=ascending',
    'http://export.arxiv.org/api/query?search_query=cat:math.CO&start=0&max_results=5&sortBy=submittedDate&sortOrder=ascending',
    'http://export.arxiv.org/api/query?search_query=cat:q-bio.NC&start=0&max_results=5&sortBy=submittedDate&sortOrder=ascending',
]
ns = {'atom': 'http://www.w3.org/2005/Atom'}
count = 0
for url in academic_queries:
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
        resp = urllib.request.urlopen(req, timeout=15)
        root = ET.fromstring(resp.read())
        for entry in root.findall('atom:entry', ns):
            title = entry.find('atom:title', ns).text.strip().replace('\n', ' ')
            abstract = entry.find('atom:summary', ns).text.strip().replace('\n', ' ')
            if len(abstract) > 200:
                count += 1
                fname = f'{BASE}/academic/academic_{count:03d}.txt'
                with open(fname, 'w') as f:
                    f.write(f'{title}\n\n{abstract}')
                print(f'  academic_{count:03d}: {title[:60]}...')
        time.sleep(1)
    except Exception as e:
        print(f'  Error: {e}')
print(f'Got {count} academic papers')

# ============ 2. LITERARY / POETRY (15) - Public domain excerpts ============
print('\n=== Creating 15 literary/poetry texts ===')
poems = [
    ('Shakespeare Sonnet 18', """Shall I compare thee to a summer's day?\nThou art more lovely and more temperate:\nRough winds do shake the darling buds of May,\nAnd summer's lease hath all too short a date;\nSometime too hot the eye of heaven shines,\nAnd often is his gold complexion dimm'd;\nAnd every fair from fair sometime declines,\nBy chance or nature's changing course untrimm'd;\nBut thy eternal summer shall not fade,\nNor lose possession of that fair thou ow'st;\nNor shall death brag thou wander'st in his shade,\nWhen in eternal lines to time thou grow'st:\nSo long as men can breathe or eyes can see,\nSo long lives this, and this gives life to thee."""),
    ('Emily Dickinson - Hope', """Hope is the thing with feathers\nThat perches in the soul,\nAnd sings the tune without the words,\nAnd never stops at all,\nAnd sweetest in the gale is heard;\nAnd sore must be the storm\nThat could abash the little bird\nThat kept so many warm.\nI have heard it in the chillest land,\nAnd on the strangest sea;\nYet, never, in extremity,\nIt asked a crumb of me."""),
    ('Walt Whitman - O Captain', """O Captain! my Captain! our fearful trip is done,\nThe ship has weather'd every rack, the prize we sought is won,\nThe port is near, the bells I hear, the people all exulting,\nWhile follow eyes the steady keel, the vessel grim and daring;\nBut O heart! heart! heart!\nO the bleeding drops of red,\nWhere on the deck my Captain lies,\nFallen cold and dead."""),
    ('Langston Hughes - Dreams', """Hold fast to dreams\nFor if dreams die\nLife is a broken-winged bird\nThat cannot fly.\nHold fast to dreams\nFor when dreams go\nLife is a barren field\nFrozen with snow."""),
    ('William Blake - Tyger', """Tyger Tyger, burning bright,\nIn the forests of the night;\nWhat immortal hand or eye,\nCould frame thy fearful symmetry?\nIn what distant deeps or skies,\nBurnt the fire of thine eyes?\nOn what wings dare he aspire?\nWhat the hand, dare seize the fire?"""),
    ('Robert Frost - Road Not Taken', """Two roads diverged in a yellow wood,\nAnd sorry I could not travel both\nAnd be one traveler, long I stood\nAnd looked down one as far as I could\nTo where it bent in the undergrowth;\nThen took the other, as just as fair,\nAnd having perhaps the better claim,\nBecause it was grassy and wanted wear;\nThough as for that the passing there\nHad worn them really about the same."""),
    ('Maya Angelou - Caged Bird', """The free bird leaps\non the back of the wind\nand floats downstream\ntill the current ends\nand dips his wings\nin the orange sun rays\nand dares to claim the sky.\nBut a bird that stalks\ndown his narrow cage\ncan seldom see through\nhis bars of rage\nhis wings are clipped and\nhis feet are tied\nso he opens his throat to sing."""),
    ('Edgar Allan Poe - Alone', """From childhood's hour I have not been\nAs others were; I have not seen\nAs others saw; I could not bring\nMy passions from a common spring.\nFrom the same source I have not taken\nMy sorrow; I could not awaken\nMy heart to joy at the same tone;\nAnd all I loved, I loved alone."""),
]

# Add prose literary excerpts (public domain)
prose_literary = [
    ('Kafka Opening - Metamorphosis', 'One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections.'),
    ('Dickens Opening - Tale of Two Cities', 'It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair.'),
    ('Austen Opening - Pride and Prejudice', 'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families, that he is considered as the rightful property of some one or other of their daughters.'),
    ('Orwell Opening - 1984', 'It was a bright cold day in April, and the clocks were striking thirteen. Winston Smith, his chin nuzzled into his breast in an effort to escape the vile wind, slipped quickly through the glass doors of Victory Mansions, though not quickly enough to prevent a swirl of gritty dust from entering along with him.'),
    ('Melville Opening - Moby Dick', 'Call me Ishmael. Some years ago, never mind how long precisely, having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world. It is a way I have of driving off the spleen and regulating the circulation.'),
    ('Tolstoy Opening - Anna Karenina', 'Happy families are all alike; every unhappy family is unhappy in its own way. Everything was in confusion in the Oblonskys house. The wife had discovered that the husband was carrying on an intrigue with a French girl, who had been a governess in their family.'),
    ('Hemingway Opening - Old Man and the Sea', 'He was an old man who fished alone in a skiff in the Gulf Stream and he had gone eighty-four days now without taking a fish. In the first forty days a boy had been with him. But after forty days without a fish the boys parents had told him that the old man was now definitely and finally salao, which is the worst form of unlucky.'),
]

for i, (title, text) in enumerate(poems + prose_literary, 1):
    fname = f'{BASE}/literary/literary_{i:03d}.txt'
    with open(fname, 'w') as f:
        f.write(f'{title}\n\n{text}')
    print(f'  literary_{i:03d}: {title}')

# ============ 3. LEGAL TEXTS (10) ============
print('\n=== Creating 10 legal texts ===')
legal_texts = [
    ('Contract Clause - Force Majeure', 'Neither party shall be liable for any failure or delay in performing their obligations under this Agreement where such failure or delay results from Force Majeure. Force Majeure means any event beyond the reasonable control of the affected party, including but not limited to acts of God, fire, flood, earthquake, epidemic, pandemic, war, terrorism, strikes, government actions, or any other event that could not have been reasonably foreseen or prevented. The affected party must notify the other party in writing within fourteen days of the Force Majeure event and must use all reasonable endeavors to mitigate the effect of the Force Majeure on the performance of its obligations.'),
    ('Terms of Service Excerpt', 'By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service. The Service is provided on an AS IS and AS AVAILABLE basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement or course of performance. The Company, its subsidiaries, affiliates, and its licensors do not warrant that the Service will function uninterrupted, secure or available at any particular time or location.'),
    ('Privacy Policy Section', 'We collect information you provide directly to us, such as when you create an account, make a purchase, subscribe to a newsletter, participate in any interactive features, fill out a form, request customer support, or otherwise communicate with us. The types of information we may collect include your name, email address, postal address, phone number, credit card information, and any other information you choose to provide. We automatically collect certain information when you use the Service, including your Internet protocol address, browser type, operating system, referring URLs, access times, and pages viewed.'),
    ('Non-Disclosure Agreement', 'The Receiving Party agrees that for a period of five years from the date of disclosure, it shall hold and maintain the Confidential Information of the Disclosing Party in strict confidence for the sole and exclusive benefit of the Disclosing Party. The Receiving Party shall carefully restrict access to Confidential Information to employees, contractors, and third parties as is reasonably required and shall require those persons to sign nondisclosure restrictions at least as protective as those in this Agreement. The Receiving Party shall not, without the prior written approval of the Disclosing Party, use for the Receiving Partys own benefit, publish, copy, or otherwise disclose to others, or permit the use by others for their benefit or to the detriment of the Disclosing Party.'),
    ('Liability Waiver', 'I hereby release, waive, discharge, and covenant not to sue the Company, its officers, directors, employees, agents, representatives, and assigns from any and all liability, claims, demands, actions, and causes of action whatsoever, directly or indirectly arising out of or related to any loss, damage, or injury, including death, that may be sustained by me related to my participation in the Activity. I understand and acknowledge that this Activity involves risks and dangers of serious bodily injury, including permanent disability, paralysis, and death. I hereby voluntarily assume full responsibility for any risks of loss, property damage, or personal injury that may be sustained as a result of participating in the Activity.'),
    ('Employment Agreement Termination', 'Either party may terminate this Agreement at any time by providing thirty days written notice to the other party. Upon termination, the Employee shall return all company property, documents, and materials, including electronic copies thereof. The Company shall pay to the Employee all accrued but unpaid salary, earned but unused vacation time, and any approved but unreimbursed expenses through the date of termination. Sections relating to confidentiality, non-competition, non-solicitation, and intellectual property shall survive termination of this Agreement and remain in full force and effect.'),
    ('Intellectual Property Assignment', 'The Contractor hereby irrevocably assigns, transfers, and conveys to the Company all right, title, and interest in and to any and all Work Product, including all Intellectual Property Rights therein. Work Product means all inventions, discoveries, developments, improvements, original works of authorship, formulas, processes, compositions of matter, software, databases, mask works, designs, methods, techniques, and trade secrets, whether or not patentable or copyrightable, that are conceived, developed, or reduced to practice by the Contractor, either alone or jointly with others, during the term of this Agreement and in connection with the Services.'),
    ('Arbitration Clause', 'Any dispute, controversy, or claim arising out of or relating to this Agreement, or the breach, termination, or invalidity thereof, shall be settled by arbitration administered by the American Arbitration Association in accordance with its Commercial Arbitration Rules. The arbitration shall be conducted by a single arbitrator selected in accordance with the aforementioned rules. The place of arbitration shall be New York, New York. The language of the arbitration shall be English. The arbitral award shall be final and binding upon the parties. Judgment upon the award rendered by the arbitrator may be entered in any court having jurisdiction thereof.'),
    ('Data Protection Clause - GDPR', 'The Processor shall process Personal Data only on documented instructions from the Controller, including with regard to transfers of personal data to a third country or an international organisation, unless required to do so by Union or Member State law to which the Processor is subject. The Processor shall ensure that persons authorised to process the Personal Data have committed themselves to confidentiality or are under an appropriate statutory obligation of confidentiality. The Processor shall implement appropriate technical and organisational measures to ensure a level of security appropriate to the risk.'),
    ('Indemnification Clause', 'Each party shall indemnify, defend, and hold harmless the other party, its officers, directors, employees, agents, successors, and assigns from and against any and all losses, damages, liabilities, deficiencies, claims, actions, judgments, settlements, interest, awards, penalties, fines, costs, or expenses of whatever kind, including reasonable attorneys fees, arising out of or resulting from any claim of a third party related to the indemnifying partys breach of any representation, warranty, or obligation under this Agreement. The indemnified party shall promptly notify the indemnifying party in writing of any claim for which indemnification is sought.'),
]
for i, (title, text) in enumerate(legal_texts, 1):
    fname = f'{BASE}/legal/legal_{i:03d}.txt'
    with open(fname, 'w') as f:
        f.write(f'{title}\n\n{text}')
    print(f'  legal_{i:03d}: {title}')

# ============ 4. JOURNALISM (10) ============
print('\n=== Creating 10 journalism-style texts ===')
journalism = [
    ('Breaking: Market Rally Continues', 'Wall Street extended its winning streak on Thursday as investors digested better-than-expected earnings reports from major technology companies. The Dow Jones Industrial Average rose 285 points, or 0.7 percent, while the broader market gained ground across nearly every sector. Trading volume was heavy, with more than 4.2 billion shares changing hands on the New York Stock Exchange. Analysts pointed to strong corporate profit margins and resilient consumer spending as key drivers of the rally. However, some strategists cautioned that valuations have become stretched and that a pullback could be imminent.'),
    ('Feature: Small Town Revival', 'When the last factory in Millbrook shuttered its doors in 2019, most people assumed the town would simply fade away. Five years later, the picture looks remarkably different. A combination of remote work migration, state tax incentives, and a grassroots revitalization effort has transformed this once-struggling community into one of the fastest-growing small towns in the region. Population has grown by 23 percent since 2020, new businesses are opening at a rate not seen since the 1970s, and the old factory building itself has been converted into a mixed-use development housing a brewery, coworking space, and artist studios.'),
    ('Investigation: Water Quality Crisis', 'An investigation spanning six months and involving analysis of more than 2,000 water quality reports has revealed that dozens of municipalities across the state have been systematically underreporting contaminant levels in their public water systems. Documents obtained through freedom of information requests show that testing protocols were modified in ways that consistently produced lower readings. State environmental officials, speaking on condition of anonymity, confirmed that the practice was widespread and had been flagged internally as early as 2018 without corrective action being taken.'),
    ('Opinion: Education Reform Needed', 'The current education system was designed for a world that no longer exists. We continue to sort students by age rather than ability, measure success through standardized tests that reward memorization over creativity, and prepare young people for jobs that are rapidly disappearing. The evidence is overwhelming that this model is failing. Graduation rates tell only part of the story. The more troubling statistic is that fewer than half of college graduates report that their education was relevant to their current work. We need a fundamental reimagining of what school is for.'),
    ('Sports: Championship Recap', 'In what many are calling the greatest championship game in the tournaments 47-year history, the underdogs from Central State completed a stunning comeback to defeat top-seeded Northern University 87-84 in triple overtime. Down by 17 points with six minutes remaining in regulation, Central State launched an improbable rally fueled by sophomore guard Marcus Williams, who scored 14 of his career-high 38 points in the final stretch. The victory marks Central States first national championship and caps a remarkable season in which the team was picked to finish last in its conference.'),
    ('Tech: AI Regulation Debate', 'As artificial intelligence systems become increasingly embedded in everyday life, the debate over how to regulate the technology has intensified. Lawmakers in several countries are grappling with fundamental questions about liability, transparency, and safety. Proponents of strict regulation argue that the potential for harm, from biased hiring algorithms to autonomous weapons, demands immediate action. Industry representatives counter that overly restrictive rules could stifle innovation and push development to less regulated jurisdictions. The European Union has taken the most aggressive approach with its AI Act.'),
    ('Health: New Treatment Breakthrough', 'Researchers at three major medical centers have published results from a Phase III clinical trial showing that a new class of immunotherapy drugs can achieve complete remission in patients with previously untreatable forms of pancreatic cancer. The study, published in the New England Journal of Medicine, followed 847 patients over four years. Those receiving the experimental treatment showed a 67 percent reduction in tumor size compared to the control group. While the results are preliminary and the treatment carries significant side effects, oncologists are calling it the most promising development in pancreatic cancer research in decades.'),
    ('Culture: Music Festival Review', 'Three days, four stages, 73 acts, and roughly 45,000 attendees descended upon Riverside Park for what has become the regions defining cultural event. The festival, now in its twelfth year, has evolved from a scrappy indie gathering into a professionally produced celebration of musical diversity. Highlights included a transcendent headlining set from veteran jazz pianist Ahmad Delacroix, a surprise acoustic performance from pop star Elena Chen in the intimate tent stage, and an incendiary hip-hop showcase that kept the crowd moving well past midnight.'),
    ('Environment: Wildfire Season Analysis', 'This years wildfire season has broken records that were set only two years ago, with more than 8.7 million acres burned across the western states by early September. Climate scientists point to a convergence of factors: prolonged drought, record high temperatures, decades of fire suppression that have left forests unnaturally dense, and expanding development into fire-prone areas. The economic toll has exceeded an estimated 26 billion dollars, including direct firefighting costs, property losses, and health impacts from smoke exposure affecting urban populations hundreds of miles from the nearest blaze.'),
    ('Profile: Tech Founder Interview', 'Sarah Chen does not look like someone who just closed a 400 million dollar funding round. Sitting in the modest conference room of her companys Oakland headquarters, wearing jeans and a faded university sweatshirt, she speaks quietly about the platform she has spent seven years building. The company, which uses machine learning to optimize supply chains for mid-sized manufacturers, now serves more than 2,300 clients across 14 countries. Revenue has grown by 340 percent over the past two years. But Chen insists the company is still in its early days.'),
]
for i, (title, text) in enumerate(journalism, 1):
    fname = f'{BASE}/journalism/journalism_{i:03d}.txt'
    with open(fname, 'w') as f:
        f.write(f'{title}\n\n{text}')
    print(f'  journalism_{i:03d}: {title}')

# ============ 5. TECHNICAL (10) ============
print('\n=== Creating 10 technical documents ===')
technical = [
    ('API Documentation - Authentication', 'Authentication is performed via OAuth 2.0 Bearer tokens. All API requests must include a valid access token in the Authorization header. To obtain an access token, send a POST request to /oauth/token with your client_id and client_secret as parameters. Tokens expire after 3600 seconds. Refresh tokens can be used to obtain new access tokens without requiring the user to re-authenticate. Rate limiting is enforced at 1000 requests per minute per token. Exceeding this limit will result in HTTP 429 responses with a Retry-After header indicating when the next request can be made.'),
    ('System Architecture Overview', 'The platform consists of three primary layers: the ingestion layer, the processing layer, and the serving layer. The ingestion layer uses Apache Kafka for real-time event streaming, supporting up to 2 million events per second with at-least-once delivery guarantees. Events are partitioned by tenant ID to ensure ordering within a single tenants data stream. The processing layer employs Apache Flink for stateful stream processing, performing enrichment, aggregation, and anomaly detection in near real-time. Results are persisted to both a PostgreSQL database for transactional queries and an Elasticsearch cluster for full-text search.'),
    ('Deployment Runbook', 'Pre-deployment checklist: 1. Verify all integration tests pass on the staging environment. 2. Confirm database migration scripts have been reviewed and approved. 3. Ensure rollback procedures are documented and tested. 4. Notify the on-call team of the planned deployment window. Deployment steps: Execute the CI/CD pipeline by merging the release branch to main. Monitor the deployment dashboard for any errors during the canary phase. The canary phase deploys to 5 percent of production traffic for 15 minutes. If error rates remain below 0.1 percent, proceed to full rollout. If error rates exceed threshold, initiate automatic rollback.'),
    ('Database Schema Design', 'The users table serves as the primary entity table with columns: id (UUID, primary key), email (VARCHAR 255, unique, not null), password_hash (VARCHAR 255, not null), created_at (TIMESTAMP WITH TIME ZONE, default NOW), updated_at (TIMESTAMP WITH TIME ZONE). A GIN index on the metadata JSONB column enables efficient querying of user attributes. The sessions table references users via a foreign key with CASCADE delete behavior. Connection pooling is managed via PgBouncer with a maximum of 200 connections per pool and transaction-level pooling mode.'),
    ('Troubleshooting Guide - Network Issues', 'If the application returns ETIMEDOUT errors, first verify DNS resolution by running nslookup against the target hostname. If DNS resolves correctly, check network connectivity using traceroute to identify where packets are being dropped. Common causes include: misconfigured security groups blocking outbound traffic on port 443, expired TLS certificates causing handshake failures, and NAT gateway throttling under high connection volume. For intermittent timeouts, enable TCP keepalive with a 60-second interval and check for connection pool exhaustion in the application logs.'),
    ('Performance Optimization Report', 'Load testing revealed that the checkout endpoint exhibits p99 latency of 4.2 seconds under sustained load of 500 concurrent users, exceeding the 2-second SLA. Root cause analysis identified three contributing factors: N+1 query pattern in the cart validation logic generating an average of 47 database queries per request, synchronous calls to the payment gateway averaging 1.8 seconds, and lack of connection pooling causing TCP handshake overhead on each database connection. Recommended mitigations: implement eager loading for cart items, introduce asynchronous payment processing with webhook confirmation, and configure connection pooling with a minimum pool size of 20.'),
    ('Code Review Guidelines', 'All pull requests must receive at least two approvals before merging. Reviewers should evaluate code for correctness, readability, performance implications, security vulnerabilities, and adherence to the team style guide. Comments should be constructive and specific, referencing line numbers and suggesting concrete alternatives where possible. Blocking comments must be prefixed with BLOCKING and include a clear explanation of why the change cannot be merged as-is. Non-blocking suggestions should be prefixed with NIT or SUGGESTION. Authors are expected to respond to all comments within one business day.'),
    ('Incident Postmortem Template', 'Incident ID: INC-2024-0847. Severity: P1. Duration: 3 hours 42 minutes. Impact: Complete service outage affecting all users in the EU-WEST-1 region. Root cause: A misconfigured load balancer health check threshold was set to 1 instead of 3, causing healthy instances to be deregistered during normal garbage collection pauses. Timeline: 14:23 UTC monitoring alerts triggered, 14:31 UTC incident commander assigned, 15:12 UTC root cause identified, 16:45 UTC health check configuration corrected, 17:05 UTC full service recovery confirmed, 18:05 UTC all-clear declared after 60-minute observation period.'),
    ('Kubernetes Deployment Manifest', 'The application is deployed as a StatefulSet with three replicas across three availability zones. Each pod requests 500m CPU and 1Gi memory with limits set to 2 CPU and 4Gi memory. Horizontal Pod Autoscaler is configured to scale between 3 and 12 replicas based on CPU utilization targeting 70 percent. Persistent volumes use the gp3 storage class with 100Gi capacity and ReadWriteOnce access mode. Liveness probes check the health endpoint every 10 seconds with a failure threshold of 3. Readiness probes check the ready endpoint every 5 seconds to ensure traffic is only routed to fully initialized pods.'),
    ('Security Audit Findings', 'The penetration test identified 4 critical, 7 high, 12 medium, and 23 low severity findings. Critical findings include: SQL injection vulnerability in the search endpoint allowing extraction of user credentials, missing rate limiting on the authentication endpoint enabling brute force attacks, hardcoded API keys in the client-side JavaScript bundle, and an insecure direct object reference allowing users to access other users invoices by modifying the invoice ID parameter. Immediate remediation is required for all critical findings before the next production release.'),
]
for i, (title, text) in enumerate(technical, 1):
    fname = f'{BASE}/technical/technical_{i:03d}.txt'
    with open(fname, 'w') as f:
        f.write(f'{title}\n\n{text}')
    print(f'  technical_{i:03d}: {title}')

# ============ 6. PERSONAL / INFORMAL (10) ============
print('\n=== Creating 10 personal/informal texts ===')
personal = [
    ('Journal Entry - Monday', 'Woke up late again. The alarm went off at 6:30 but I just could not get out of bed. Finally dragged myself up around 7:15 and barely made it to the office on time. Had back-to-back meetings all morning which was exhausting. Grabbed a sandwich from the place on the corner for lunch. It was okay I guess. The afternoon was better, actually got some real work done on the project. Left around 5:30 and went for a quick run before dinner. Made pasta. Watched some TV. Nothing special but sometimes thats exactly what you need.'),
    ('Email to Friend', 'Hey! So I finally booked those flights to Portugal. Were going in October, the second week. I got us tickets into Lisbon and then I figured we could rent a car and drive up to Porto. Theres this tiny village called Monsaraz that Sarah told me about, apparently its incredible. Let me know if you want me to book the Airbnb or if you want to look for one. Also are you still vegetarian? I need to know for restaurant planning lol. Cant wait!'),
    ('Product Review', 'I bought this blender about three months ago and honestly its been great. Handles frozen fruit no problem, makes smoothies in like 30 seconds, and its way quieter than my old one. The only downside is the lid doesnt seal super well if you fill it past the max line, which I learned the hard way when I got mango smoothie all over my ceiling. Wouldnt recommend that. But overall for the price its really solid. Ive used it pretty much every day and it still works perfectly.'),
    ('Recipe Blog Post', 'Okay so this banana bread recipe is the one Ive been making for years and it never fails. You need 3 really ripe bananas like the grosser the better, a third cup of melted butter, three quarters cup of sugar, one egg, a teaspoon of vanilla, a teaspoon of baking soda, a pinch of salt, and one and a half cups of flour. Mash the bananas, mix in the butter, then add everything else. Pour into a greased loaf pan and bake at 350 for about an hour. The trick is to not overmix the batter. Lumpy is fine. Trust me.'),
    ('Social Media Rant', 'Can we talk about how every single streaming service now has ads even on the paid plans? Like I am literally paying you twelve dollars a month and you still want me to watch a 30 second ad before my show? This is ridiculous. Remember when we all cut cable because we were tired of ads? And now we have like seven different subscriptions that all have ads anyway? We have come full circle and somehow its worse because at least cable gave you everything in one place.'),
    ('Moving Day Story', 'The move was an absolute disaster. The truck showed up two hours late, then it started raining, then we realized the couch wouldnt fit through the apartment door. My buddy Carlos had the genius idea to try the window which actually worked but took about 45 minutes and a lot of creative problem solving. By 8pm we had everything inside but nothing unpacked and we were all completely wiped. Ordered pizza and sat on the floor eating it because the table was buried under boxes somewhere. But hey, new apartment. New chapter.'),
    ('Parent Forum Post', 'My 3 year old has decided that she will only eat food that is the color orange. Im not even kidding. Carrots, sweet potatoes, oranges, cheddar cheese, those orange crackers. If its not orange she wont touch it. My pediatrician says its a phase and not to worry too much as long as shes getting enough calories. Has anyone else dealt with this? How long did it last? Im running out of orange food ideas and Im starting to worry about nutrition.'),
    ('Vacation Recap', 'Just got back from a week in Costa Rica and wow. The highlight was definitely the cloud forest in Monteverde. You literally walk through clouds, its surreal. We saw like four different species of hummingbirds and a sloth just hanging out in a tree right next to the path. The zip lining was terrifying but amazing. Food was incredible everywhere we went. Only complaint is the roads are pretty rough outside the main cities. Our rental car took a beating. But honestly it was the best trip weve taken in years.'),
    ('Tech Support Chat', 'Hi, my laptop keeps freezing every time I try to open more than like 3 tabs in Chrome. Its a 2021 MacBook Pro so it shouldnt be doing this. Ive tried restarting, clearing the cache, and even reinstalling Chrome. Still happens. Activity Monitor shows Chrome using like 8GB of RAM which seems insane. Is there something else I should try? I need this fixed because I work from home and cant really function with a browser that crashes every 20 minutes.'),
    ('Gratitude List', 'Things Im grateful for today: My mom called just to chat and it made my whole morning better. The coffee shop barista remembered my order. Found a twenty dollar bill in my coat pocket from last winter. My team at work actually listened to my idea in the meeting today. The sunset was absolutely gorgeous on my drive home. My dog was so excited to see me when I walked in the door. Sometimes its the small stuff that adds up to a really good day.'),
]
for i, (title, text) in enumerate(personal, 1):
    fname = f'{BASE}/personal/personal_{i:03d}.txt'
    with open(fname, 'w') as f:
        f.write(f'{title}\n\n{text}')
    print(f'  personal_{i:03d}: {title}')

# ============ 7. BUSINESS (10) ============
print('\n=== Creating 10 business documents ===')
business = [
    ('Quarterly Earnings Summary', 'Total revenue for Q3 2024 reached 4.7 billion dollars, representing a 12 percent increase year-over-year and exceeding analyst consensus estimates by approximately 200 million dollars. Gross margins expanded to 68.3 percent, up from 65.1 percent in the prior year quarter, driven primarily by improved operational efficiency and favorable product mix. Operating expenses as a percentage of revenue declined to 41.2 percent from 43.8 percent. Free cash flow generation was robust at 1.1 billion dollars, enabling the company to reduce net debt by 800 million dollars while returning 300 million dollars to shareholders through dividends and share repurchases.'),
    ('Marketing Strategy Memo', 'Following analysis of our Q2 campaign performance data, we recommend a significant reallocation of the digital marketing budget for the upcoming quarter. Paid social channels delivered a customer acquisition cost of 47 dollars, compared to 28 dollars for search engine marketing and 19 dollars for email campaigns targeting existing customers. We propose reducing paid social spend by 35 percent and redirecting those funds toward search and email automation. Additionally, our A/B testing program identified that video content generates 3.2 times higher engagement than static images across all platforms. We recommend increasing video production capacity accordingly.'),
    ('Board Meeting Minutes', 'The Board of Directors convened at 10:00 AM on March 15, 2024. All seven directors were present. The minutes of the previous meeting held on December 12, 2023 were approved unanimously. The Chief Financial Officer presented the annual financial results, noting record revenue and margin expansion. The board approved the proposed annual dividend of 2.40 dollars per share, payable on April 30 to shareholders of record as of April 15. The Compensation Committee presented its recommendations for executive compensation adjustments. After discussion, the board approved a 7 percent base salary increase for the CEO and performance-based equity grants for the senior leadership team.'),
    ('Project Status Update', 'Project Atlas is currently in Phase 3 of 5 and tracking two weeks behind the original timeline due to unexpected complexity in the data migration workstream. The delay is attributed to legacy system data quality issues that required development of additional cleansing and transformation logic. The technical team has proposed a revised approach that should recover one week of the delay. Key milestones completed this month include successful integration testing of the payment processing module, completion of user acceptance testing for the dashboard, and deployment of the API gateway to the staging environment. Three critical path items remain for Phase 3 completion.'),
    ('Vendor Evaluation Report', 'After evaluating six enterprise CRM platforms against our defined requirements matrix, we recommend proceeding with Vendor C for the following reasons. Vendor C scored highest in overall functionality with 87 out of 100 points, compared to 82 for Vendor A and 79 for Vendor B. Total cost of ownership over five years is estimated at 2.3 million dollars, which is 15 percent lower than the next closest option. Implementation timeline is projected at 14 weeks, the shortest among all evaluated vendors. Customer references were uniformly positive, with particular praise for the vendors implementation methodology and ongoing support quality.'),
    ('Employee Onboarding Guide', 'Welcome to the team. Your first two weeks are designed to help you build context and relationships before diving into project work. During Week 1, you will complete mandatory compliance training, set up your development environment, and attend introduction sessions with each department lead. Your onboarding buddy, assigned on your first day, will be your primary resource for questions about team norms, tools, and processes. During Week 2, you will shadow a senior team member on active project work, complete your first code review, and attend your first sprint planning session. Your 30-60-90 day goals will be established in collaboration with your manager during your first one-on-one.'),
    ('Risk Assessment Brief', 'The proposed expansion into the Southeast Asian market presents moderate to high risk across three dimensions. Regulatory risk is elevated due to evolving data localization requirements in Indonesia and Vietnam, which could necessitate significant infrastructure investment. Currency risk is material given the historical volatility of regional currencies against the US dollar. Competitive risk is moderate, with two established local players controlling approximately 60 percent of the addressable market. Mitigation strategies include establishing local legal entities, implementing natural hedging through in-country revenue and expense matching, and pursuing a partnership-first market entry strategy.'),
    ('Customer Success Playbook', 'The 90-day customer onboarding process consists of three phases. Phase 1, Implementation, spans days 1 through 30 and includes technical setup, data migration, and initial configuration. The assigned Customer Success Manager conducts a kickoff call within the first 48 hours to align on objectives, success criteria, and communication cadence. Phase 2, Activation, covers days 31 through 60 and focuses on user training, workflow optimization, and establishing usage benchmarks. Phase 3, Value Realization, spans days 61 through 90 and involves measuring outcomes against the defined success criteria, identifying expansion opportunities, and transitioning to the ongoing relationship management model.'),
    ('Annual Budget Proposal', 'The proposed FY2025 operating budget totals 127.4 million dollars, representing a 9 percent increase over the current fiscal year. The largest increases are concentrated in three areas: engineering headcount expansion of 45 positions to support the product roadmap at an incremental cost of 6.8 million dollars, cloud infrastructure scaling to accommodate projected 40 percent user growth at 3.2 million dollars, and go-to-market investment in two new geographic regions at 2.1 million dollars. These investments are projected to generate incremental annual recurring revenue of 18 to 22 million dollars within 18 months of deployment.'),
    ('Partnership Proposal', 'We propose a strategic partnership between our organizations to jointly develop and market an integrated solution for the healthcare vertical. The proposed structure involves a revenue-sharing model with a 60/40 split favoring the primary seller on each transaction. Joint development costs would be shared equally, with an estimated combined investment of 3.5 million dollars over 18 months. The addressable market for the integrated solution is estimated at 2.1 billion dollars annually, with a realistic first-year target of capturing 0.5 percent market share. Key advantages of the partnership include complementary technology capabilities, non-overlapping customer bases, and combined domain expertise.'),
]
for i, (title, text) in enumerate(business, 1):
    fname = f'{BASE}/business/business_{i:03d}.txt'
    with open(fname, 'w') as f:
        f.write(f'{title}\n\n{text}')
    print(f'  business_{i:03d}: {title}')

# ============ 8. MEDICAL (10) ============
print('\n=== Creating 10 medical texts ===')
medical = [
    ('Clinical Case Report', 'A 54-year-old male presented to the emergency department with acute onset chest pain radiating to the left arm, associated with diaphoresis and dyspnea. The patient reported the pain began approximately 90 minutes prior to arrival while climbing stairs. Past medical history is significant for hypertension, type 2 diabetes mellitus, and hyperlipidemia. Current medications include metformin 1000mg twice daily, lisinopril 20mg daily, and atorvastatin 40mg daily. On examination, the patient appeared diaphoretic and in moderate distress. Blood pressure was 158/94 mmHg, heart rate 102 bpm, respiratory rate 22, and oxygen saturation 94 percent on room air. ECG revealed ST-segment elevation in leads V1 through V4.'),
    ('Drug Information Leaflet', 'Metformin hydrochloride is an oral antihyperglycemic agent used in the management of type 2 diabetes mellitus. The recommended starting dose is 500mg twice daily or 850mg once daily, administered with meals to reduce gastrointestinal side effects. The maximum recommended daily dose is 2550mg. Common adverse effects include nausea, vomiting, diarrhea, flatulence, and abdominal discomfort, which typically resolve with continued use. The most serious adverse effect is lactic acidosis, which is rare but potentially fatal. Metformin is contraindicated in patients with severe renal impairment, acute or chronic metabolic acidosis, and in patients undergoing radiologic studies involving intravascular administration of iodinated contrast materials.'),
    ('Surgical Procedure Note', 'Procedure: Laparoscopic cholecystectomy. Anesthesia: General endotracheal. The patient was placed in supine position with arms tucked. After induction of general anesthesia, a Veress needle was inserted at the umbilicus and pneumoperitoneum was established to 15 mmHg. Four trocars were placed in standard positions. The gallbladder was identified and the cystic duct and cystic artery were dissected within the triangle of Calot. Critical view of safety was achieved and documented photographically. The cystic duct and cystic artery were clipped with titanium clips and divided. The gallbladder was dissected from the liver bed using electrocautery and removed through the umbilical port in a specimen bag. Hemostasis was confirmed and all ports were removed under direct visualization.'),
    ('Public Health Advisory', 'The Department of Health is issuing this advisory regarding an increase in reported cases of respiratory syncytial virus in the metropolitan area. Over the past four weeks, emergency department visits for RSV-related illness have increased by 340 percent compared to the same period last year. The majority of hospitalizations have occurred in children under 24 months and adults over 65 years of age. Healthcare providers are advised to implement enhanced infection control measures and consider prophylactic treatment with palivizumab for high-risk infants. The public is encouraged to practice frequent handwashing, avoid close contact with sick individuals, and seek medical attention for symptoms including persistent cough, wheezing, and difficulty breathing.'),
    ('Pathology Report', 'Specimen: Right breast, needle core biopsy. Clinical history: 52-year-old female with a 1.8 cm spiculated mass in the right upper outer quadrant identified on screening mammography, classified as BI-RADS 5. Gross description: Received in formalin are four cores of tan-white tissue, each measuring 1.2 cm in length and 0.1 cm in diameter. The entire specimen is submitted in one cassette. Microscopic description: Sections reveal infiltrating ductal carcinoma, moderately differentiated, Nottingham grade 2 of 3. Tumor cells are arranged in cords, nests, and tubular structures within a desmoplastic stroma. Nuclear grade is intermediate with occasional mitotic figures. No lymphovascular invasion is identified. Margins cannot be assessed on core biopsy material.'),
    ('Discharge Summary', 'The patient is a 67-year-old female admitted for community-acquired pneumonia. She presented with five days of productive cough, fever to 39.2 degrees Celsius, and progressive dyspnea. Chest radiograph on admission showed right lower lobe consolidation. Blood cultures were negative. Sputum culture grew Streptococcus pneumoniae sensitive to penicillin. She was treated with intravenous ceftriaxone for 48 hours followed by oral amoxicillin-clavulanate. Oxygen requirements peaked at 3 liters per minute nasal cannula on hospital day 2 and were weaned to room air by hospital day 4. She is discharged in stable condition on hospital day 5 with a prescription for oral amoxicillin-clavulanate 875/125mg twice daily for an additional 5 days.'),
    ('Clinical Trial Protocol Summary', 'This is a phase 2, randomized, double-blind, placebo-controlled study to evaluate the efficacy and safety of compound XR-7291 in patients with moderate to severe rheumatoid arthritis who have had an inadequate response to methotrexate. Approximately 240 patients will be randomized in a 1:1:1 ratio to receive XR-7291 200mg, XR-7291 400mg, or placebo administered subcutaneously every two weeks for 24 weeks. The primary endpoint is the proportion of patients achieving ACR50 response at Week 12. Key secondary endpoints include change from baseline in DAS28-CRP at Week 24, ACR20 and ACR70 response rates, and change from baseline in HAQ-DI score. Safety assessments include adverse events, laboratory parameters, and immunogenicity.'),
    ('Radiology Report', 'Examination: CT chest with contrast. Clinical indication: Persistent cough, weight loss, 45 pack-year smoking history. Findings: There is a 3.2 x 2.8 cm irregular soft tissue mass in the right upper lobe with spiculated margins and pleural retraction. The mass demonstrates heterogeneous enhancement following contrast administration. There is associated right hilar lymphadenopathy with the largest node measuring 1.8 cm in short axis. A 6 mm non-calcified nodule is identified in the left lower lobe. No pleural effusion is seen. The heart is normal in size. There is mild coronary artery calcification. The visualized portions of the upper abdomen are unremarkable. Impression: Right upper lobe mass highly suspicious for primary lung malignancy. Right hilar lymphadenopathy suggesting regional nodal involvement.'),
    ('Nursing Assessment Note', 'Patient is alert and oriented to person, place, time, and situation. Vital signs at 0800: temperature 37.1 degrees Celsius, blood pressure 132/78 mmHg, heart rate 76 bpm regular, respiratory rate 16, oxygen saturation 98 percent on room air. Pain assessed at 3 out of 10, localized to the right lower quadrant surgical site. Surgical dressing is clean, dry, and intact with no evidence of drainage or erythema. Bowel sounds are present in all four quadrants. Patient tolerated a clear liquid diet at breakfast without nausea. Foley catheter output measured at 240 mL over the past 8 hours, urine is clear and yellow. Sequential compression devices are in place bilaterally. Fall risk assessment score is 45, indicating moderate risk. Patient is ambulatory with assistance.'),
    ('Mental Health Assessment', 'The patient is a 28-year-old female presenting for initial psychiatric evaluation with chief complaint of persistent low mood and difficulty concentrating for the past three months. She reports decreased appetite with unintentional weight loss of approximately 8 pounds, insomnia with difficulty initiating sleep, low energy, feelings of worthlessness, and diminished interest in previously enjoyed activities. She denies suicidal ideation, homicidal ideation, auditory or visual hallucinations, and substance use. PHQ-9 score is 18, indicating moderately severe depression. GAD-7 score is 12, indicating moderate anxiety. Mental status examination reveals a cooperative young woman with congruent affect, psychomotor retardation, and goal-directed thought process without looseness of associations or tangentiality.'),
]
for i, (title, text) in enumerate(medical, 1):
    fname = f'{BASE}/medical/medical_{i:03d}.txt'
    with open(fname, 'w') as f:
        f.write(f'{title}\n\n{text}')
    print(f'  medical_{i:03d}: {title}')

# ============ 9. POLITICAL (5) ============
print('\n=== Creating 5 political texts ===')
political = [
    ('Policy Proposal - Infrastructure', 'The proposed Infrastructure Renewal Act would authorize 420 billion dollars in federal spending over ten years to rebuild the nations deteriorating transportation network. The legislation allocates 180 billion dollars for highway and bridge repair, targeting the estimated 46,154 structurally deficient bridges currently in service. An additional 120 billion dollars would fund expansion of public transit systems in metropolitan areas with populations exceeding 500,000. The remaining 120 billion dollars would support rural broadband deployment, water system modernization, and electric vehicle charging infrastructure. Funding mechanisms include a combination of increased fuel taxes, public-private partnerships, and reallocation of existing transportation appropriations.'),
    ('Campaign Speech Excerpt', 'When I talk to families in this district, I hear the same concerns over and over again. They worry about whether they can afford to send their kids to college. They worry about what happens if someone in their family gets sick. They worry about whether there will be good jobs for their children when they grow up. These are not partisan concerns. These are human concerns. And they deserve serious answers, not talking points. I am running for this office because I believe we can do better. Not by tearing each other down, but by building something together that works for everyone in this community.'),
    ('Legislative Analysis', 'Senate Bill 1247 would amend the existing telecommunications regulatory framework to impose net neutrality requirements on internet service providers. The bill prohibits blocking, throttling, and paid prioritization of lawful internet traffic. It grants enforcement authority to the Federal Communications Commission with the power to levy fines of up to 2 million dollars per violation. Industry groups estimate compliance costs at approximately 1.4 billion dollars annually across the sector. Consumer advocacy organizations argue that the bill does not go far enough, noting the absence of provisions addressing data caps and zero-rating practices. The Congressional Budget Office estimates the bill would generate 340 million dollars in fine revenue over ten years.'),
    ('UN Resolution Summary', 'The General Assembly adopted Resolution A/RES/78/142 by a vote of 143 in favor, 9 against, with 25 abstentions. The resolution calls upon all Member States to accelerate the implementation of the 2030 Agenda for Sustainable Development, with particular emphasis on climate action, poverty eradication, and gender equality. The resolution further urges developed countries to fulfill their commitment of mobilizing 100 billion dollars annually in climate finance for developing nations. It requests the Secretary-General to submit a comprehensive progress report to the General Assembly at its seventy-ninth session, including recommendations for addressing implementation gaps.'),
    ('Electoral Commission Report', 'The Electoral Commission certifies the results of the general election held on November 5, 2024. Total registered voters numbered 168,342,876. Total ballots cast were 131,276,493, representing a turnout rate of 78.0 percent, the highest since 1960. Of ballots cast, 129,891,007 were certified as valid, with 1,385,486 rejected due to irregularities including incomplete markings, duplicate submissions, and late receipt of mail-in ballots. Provisional ballots totaled 2,847,291, of which 2,103,445 were ultimately accepted after verification. The commission received 347 formal complaints regarding polling place operations, of which 12 were substantiated and referred for further investigation.'),
]
for i, (title, text) in enumerate(political, 1):
    fname = f'{BASE}/political/political_{i:03d}.txt'
    with open(fname, 'w') as f:
        f.write(f'{title}\n\n{text}')
    print(f'  political_{i:03d}: {title}')

# ============ 10. AI-GENERATED (10) ============
print('\n=== Creating 10 AI-style texts ===')
ai_generated = [
    ('AI Essay - Climate Change', 'Climate change represents one of the most pressing challenges facing humanity today. The scientific consensus is clear: human activities, particularly the burning of fossil fuels, are driving unprecedented changes in global climate patterns. Rising temperatures, melting ice caps, and increasingly severe weather events serve as stark reminders of the urgency of this crisis. It is crucial that we take immediate and decisive action to mitigate the impacts of climate change. This requires a multifaceted approach encompassing renewable energy adoption, carbon emission reduction, and sustainable development practices. By working together as a global community, we can build a more sustainable future for generations to come.'),
    ('AI Blog Post - Productivity', 'In todays fast-paced world, productivity has become more important than ever. Whether you are a student, a professional, or an entrepreneur, the ability to manage your time effectively can make or break your success. Here are five proven strategies to boost your productivity. First, prioritize your tasks using the Eisenhower Matrix, which categorizes tasks based on urgency and importance. Second, implement the Pomodoro Technique, working in focused 25-minute intervals followed by short breaks. Third, minimize distractions by creating a dedicated workspace. Fourth, leverage technology tools such as project management software and calendar apps. Fifth, practice self-care, as adequate sleep, exercise, and nutrition are fundamental to sustained productivity.'),
    ('AI Product Description', 'Introducing the revolutionary SmartFlow Pro water purification system, designed to transform the way you think about hydration. Utilizing cutting-edge multi-stage filtration technology, the SmartFlow Pro removes up to 99.9 percent of contaminants while preserving essential minerals for optimal health. The sleek, modern design seamlessly integrates into any kitchen aesthetic, while the intuitive touch-screen display provides real-time water quality metrics and filter life monitoring. With its eco-friendly approach, the SmartFlow Pro eliminates the need for single-use plastic bottles, helping you reduce your environmental footprint. Experience the difference that truly pure water can make in your daily life.'),
    ('AI Research Summary', 'This comprehensive study examines the multifaceted impact of remote work on employee productivity, well-being, and organizational culture. Drawing on data from a survey of 5,000 knowledge workers across diverse industries, our findings reveal several key insights. Firstly, remote workers reported a 23 percent increase in self-assessed productivity, attributed primarily to reduced commuting time and fewer workplace interruptions. Secondly, while flexibility was consistently cited as the primary benefit of remote work, 67 percent of respondents reported feelings of isolation and difficulty maintaining work-life boundaries. Thirdly, organizations that implemented structured virtual team-building activities and clear communication protocols experienced significantly higher employee satisfaction scores.'),
    ('AI LinkedIn Post', 'Excited to share that after an incredible journey of growth and learning, I have been promoted to Senior Director of Product Innovation at TechVentures. This milestone would not have been possible without the unwavering support of my amazing team, mentors, and colleagues who have challenged me to think bigger and push boundaries. Over the past three years, we have launched 12 products, expanded into 4 new markets, and grown our team from 15 to 78 talented individuals. I am deeply grateful for every experience that has shaped my leadership journey. Looking forward to the next chapter of innovation and impact. What is one piece of career advice that has been most impactful for you?'),
    ('AI Cover Letter', 'I am writing to express my strong interest in the Senior Software Engineer position at Innovatech Solutions. With over eight years of experience in full-stack development and a proven track record of delivering scalable, high-performance applications, I am confident that my skills and experience align well with the requirements of this role. In my current position at TechDynamics, I have led the development of a microservices architecture that reduced system latency by 40 percent and improved deployment frequency from monthly to daily releases. I am particularly drawn to Innovatech Solutions commitment to innovation and its mission to democratize access to technology. I would welcome the opportunity to bring my expertise in cloud architecture, team leadership, and agile methodologies to your organization.'),
    ('AI How-To Guide', 'Getting started with machine learning can seem daunting, but with the right approach, anyone can begin building intelligent applications. In this comprehensive guide, we will walk you through the essential steps to begin your machine learning journey. First, establish a solid foundation in Python programming and key libraries such as NumPy, Pandas, and Scikit-learn. Next, familiarize yourself with fundamental concepts including supervised and unsupervised learning, feature engineering, and model evaluation metrics. It is important to start with simple algorithms such as linear regression and decision trees before progressing to more complex architectures. Practice is essential, so work through datasets available on platforms like Kaggle to build practical experience.'),
    ('AI Company About Page', 'At Nexus Innovations, we believe that technology should empower people, not complicate their lives. Founded in 2018, our company has grown from a small startup with a bold vision to a global leader in AI-powered business solutions. Our diverse team of over 500 talented professionals spans 12 countries, united by a shared passion for innovation and a commitment to excellence. We have helped more than 3,000 organizations across industries transform their operations, reduce costs, and unlock new opportunities for growth. Our core values of integrity, collaboration, and continuous improvement guide everything we do. We are not just building technology; we are building a better future for businesses and communities around the world.'),
    ('AI Email Newsletter', 'Welcome to this weeks edition of The Innovation Digest, your curated source for the latest trends in technology and business. This week, we explore three transformative developments shaping the future of work. The rise of AI copilots in the workplace is accelerating, with major enterprise software providers integrating generative AI capabilities into their platforms. Meanwhile, the four-day work week movement continues to gain momentum, with several Fortune 500 companies announcing pilot programs. Finally, we examine how blockchain technology is revolutionizing supply chain transparency, enabling consumers to trace products from source to shelf. Read on for in-depth analysis and expert commentary on each of these exciting developments.'),
    ('AI Motivational Content', 'Success is not a destination; it is a journey of continuous growth and self-improvement. Every great achievement begins with a single step, and every setback is an opportunity to learn and evolve. The most successful people in history did not achieve greatness by avoiding failure; they achieved it by embracing failure as a teacher and persevering through adversity. Remember that your potential is limitless. The only barriers that truly exist are the ones you create in your own mind. Today is the perfect day to take that first step toward the life you have always envisioned. Believe in yourself, stay committed to your goals, and never stop learning. The best version of you is waiting to emerge.'),
]
for i, (title, text) in enumerate(ai_generated, 1):
    fname = f'{BASE}/mixed/ai_style_{i:03d}.txt'
    with open(fname, 'w') as f:
        f.write(f'{title}\n\n{text}')
    print(f'  ai_style_{i:03d}: {title}')

# ============ MANIFEST ============
print('\n=== Creating manifest ===')
manifest = {'total': 0, 'categories': {}}
for cat in ['academic', 'literary', 'legal', 'journalism', 'technical', 'personal', 'business', 'medical', 'political', 'mixed']:
    path = f'{BASE}/{cat}'
    files = sorted([f for f in os.listdir(path) if f.endswith('.txt')])
    manifest['categories'][cat] = {'count': len(files), 'files': files}
    manifest['total'] += len(files)

with open(f'{BASE}/manifest.json', 'w') as f:
    json.dump(manifest, f, indent=2)

print(f'\n=== TOTAL: {manifest["total"]} test documents created ===')
for cat, info in manifest['categories'].items():
    print(f'  {cat}: {info["count"]}')
