//! Self-contained HTML report generation.
//!
//! Produces a single HTML file with embedded CSS — no external dependencies.
//! Includes feature comparison tables, confidence visualization, and
//! anomaly heatmap (when tampering data is available).

use super::engine::UnifiedScore;
use crate::utils::errors::Result;

/// Render a unified score as a self-contained HTML report.
pub fn render(score: &UnifiedScore) -> Result<String> {
    let mut html = String::with_capacity(8192);

    html.push_str("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
    html.push_str("<meta charset=\"UTF-8\">\n");
    html.push_str("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
    html.push_str("<title>Provenance — Authorship Analysis Report</title>\n");
    html.push_str("<style>\n");
    html.push_str(CSS);
    html.push_str("</style>\n</head>\n<body>\n");

    // Header
    html.push_str("<header>\n");
    html.push_str("<h1>Provenance</h1>\n");
    html.push_str("<p class=\"subtitle\">Authorship Analysis Report</p>\n");
    html.push_str("</header>\n<main>\n");

    // File info section
    render_file_section(&mut html, score);

    // Lexical section
    render_lexical_section(&mut html, score);

    // Syntactic section
    render_syntactic_section(&mut html, score);

    // Stylometric section
    render_stylometric_section(&mut html, score);

    // Readability section
    render_readability_section(&mut html, score);

    // Function words section
    render_function_words_section(&mut html, score);

    // Comparison section
    if score.comparison.is_some() {
        render_comparison_section(&mut html, score);
    }

    // Tampering section
    if score.forensic_report.tampering.risk_score > 0.0 {
        render_tampering_section(&mut html, score);
    }

    // Audit trail
    render_audit_section(&mut html, score);

    html.push_str("</main>\n");
    html.push_str("<footer>\n");
    html.push_str(&format!(
        "<p>Generated by Provenance v{} &mdash; {}</p>\n",
        score.audit.software_version, score.audit.timestamp
    ));
    html.push_str("</footer>\n</body>\n</html>");

    Ok(html)
}

fn render_file_section(html: &mut String, score: &UnifiedScore) {
    html.push_str("<section>\n<h2>File Information</h2>\n<table>\n");
    row(html, "File", &score.forensic_report.metadata.file_name);
    row(html, "Size", &format!("{} bytes", score.forensic_report.metadata.file_size));
    row(html, "Format", &format!("{}", score.forensic_report.format.detected_type));
    row(html, "Encoding", &score.forensic_report.format.encoding);
    row(html, "SHA-256", &score.forensic_report.integrity.sha256);

    if !score.forensic_report.format.extension_matches {
        html.push_str("<tr class=\"warning\"><td>Warning</td><td>");
        if let Some(ref w) = score.forensic_report.format.mismatch_warning {
            html.push_str(&escape(w));
        }
        html.push_str("</td></tr>\n");
    }

    if let Some(ref doc) = score.forensic_report.metadata.document_metadata {
        if let Some(ref title) = doc.title { row(html, "Title", title); }
        if let Some(ref author) = doc.author { row(html, "Doc Author", author); }
        if let Some(ref tool) = doc.creator_tool { row(html, "Created With", tool); }
        if let Some(rev) = doc.revision_count { row(html, "Revisions", &rev.to_string()); }
        if let Some(pages) = doc.page_count { row(html, "Pages", &pages.to_string()); }
    }

    html.push_str("</table>\n</section>\n");
}

fn render_lexical_section(html: &mut String, score: &UnifiedScore) {
    let lex = &score.analysis_result.lexical;
    html.push_str("<section>\n<h2>Lexical Analysis</h2>\n<table>\n");
    row(html, "Total Words", &lex.total_words.to_string());
    row(html, "Unique Words", &lex.unique_words.to_string());
    row(html, "MATTR", &format!("{:.4}", lex.mattr));
    row(html, "Yule's K", &format!("{:.2}", lex.yules_k));
    row(html, "Honor&eacute;'s R", &format!("{:.2}", lex.honores_r));
    row(html, "Hapax Legomena", &format!("{} ({:.1}%)", lex.hapax_legomena, lex.hapax_ratio * 100.0));
    row(html, "Avg Word Length", &format!("{:.2}", lex.avg_word_length));
    html.push_str("</table>\n</section>\n");
}

fn render_syntactic_section(html: &mut String, score: &UnifiedScore) {
    let syn = &score.analysis_result.syntactic;
    html.push_str("<section>\n<h2>Syntactic Analysis</h2>\n<table>\n");
    row(html, "Total Sentences", &syn.total_sentences.to_string());
    row(html, "Avg Words/Sentence", &format!("{:.1}", syn.avg_words_per_sentence));
    row(html, "Length Variance", &format!("{:.1}", syn.sentence_length_variance));
    row(html, "Declarative", &syn.declarative_count.to_string());
    row(html, "Interrogative", &format!("{} ({:.1}%)", syn.interrogative_count, syn.interrogative_ratio * 100.0));
    row(html, "Exclamatory", &format!("{} ({:.1}%)", syn.exclamatory_count, syn.exclamatory_ratio * 100.0));
    row(html, "Passive Voice", &format!("{:.1}%", syn.passive_voice_ratio * 100.0));
    html.push_str("</table>\n</section>\n");
}

fn render_stylometric_section(html: &mut String, score: &UnifiedScore) {
    let sty = &score.analysis_result.stylometric;
    html.push_str("<section>\n<h2>Stylometric Analysis</h2>\n<table>\n");
    row(html, "Paragraphs", &sty.paragraph_count.to_string());
    row(html, "Contractions", &format!("{} ({:.2}%)", sty.contraction_count, sty.contraction_ratio * 100.0));
    row(html, "Hedge Words", &format!("{} ({:.2}%)", sty.hedge_word_count, sty.hedge_word_ratio * 100.0));
    row(html, "Intensifiers", &format!("{} ({:.2}%)", sty.intensifier_count, sty.intensifier_ratio * 100.0));
    row(html, "Em-dashes", &sty.em_dash_count.to_string());
    row(html, "Ellipses", &sty.ellipsis_count.to_string());
    row(html, "Parentheticals", &sty.parenthetical_count.to_string());
    html.push_str("</table>\n</section>\n");
}

fn render_readability_section(html: &mut String, score: &UnifiedScore) {
    let sem = &score.analysis_result.semantic;
    html.push_str("<section>\n<h2>Readability &amp; Discourse</h2>\n<table>\n");
    row(html, "Flesch-Kincaid Grade", &format!("{:.1}", sem.flesch_kincaid_grade));
    row(html, "Gunning Fog Index", &format!("{:.1}", sem.gunning_fog_index));
    row(html, "Coleman-Liau Index", &format!("{:.1}", sem.coleman_liau_index));
    row(html, "Discourse Markers", &format!("{:.2}%", sem.discourse_marker_ratio * 100.0));
    html.push_str("</table>\n</section>\n");
}

fn render_function_words_section(html: &mut String, score: &UnifiedScore) {
    let fw = &score.analysis_result.function_words;
    html.push_str("<section>\n<h2>Function Words</h2>\n");
    html.push_str(&format!("<p>Ratio: {:.1}% &mdash; {} distinct function words used</p>\n",
        fw.function_word_ratio * 100.0, fw.function_word_diversity));

    let mut top_fw: Vec<(&String, &f64)> = fw.frequencies.iter().collect();
    top_fw.sort_by(|a, b| b.1.partial_cmp(a.1).unwrap_or(std::cmp::Ordering::Equal));

    html.push_str("<table>\n<tr><th>Word</th><th>Freq (per 1000)</th><th></th></tr>\n");
    let max_freq = top_fw.first().map(|(_, f)| **f).unwrap_or(1.0);
    for (word, freq) in top_fw.iter().take(15) {
        let bar_width = (**freq / max_freq * 100.0) as u32;
        html.push_str(&format!(
            "<tr><td><code>{}</code></td><td>{:.1}</td><td><div class=\"bar\" style=\"width:{bar_width}%\"></div></td></tr>\n",
            escape(word), freq
        ));
    }
    html.push_str("</table>\n</section>\n");
}

fn render_comparison_section(html: &mut String, score: &UnifiedScore) {
    let comp = score.comparison.as_ref().unwrap();

    let conf_class = if comp.confidence.value >= 0.85 {
        "high"
    } else if comp.confidence.value >= 0.65 {
        "medium"
    } else {
        "low"
    };

    html.push_str("<section>\n<h2>Authorship Comparison</h2>\n");
    html.push_str(&format!(
        "<div class=\"confidence {conf_class}\">\n\
         <span class=\"label\">Match: {}</span>\n\
         <span class=\"value\">{:.1}%</span>\n\
         <span class=\"level\">{:?}</span>\n\
         </div>\n",
        escape(&comp.author_name),
        comp.confidence.value * 100.0,
        comp.confidence.level
    ));

    if !comp.feature_distances.is_empty() {
        html.push_str("<table>\n<tr><th>Feature</th><th>Expected</th><th>Actual</th><th>Distance</th></tr>\n");
        for fd in &comp.feature_distances {
            html.push_str(&format!(
                "<tr><td>{}</td><td>{:.4}</td><td>{:.4}</td><td>{:.4}</td></tr>\n",
                escape(&fd.feature_name), fd.expected, fd.actual, fd.normalized_distance
            ));
        }
        html.push_str("</table>\n");
    }

    html.push_str("</section>\n");
}

fn render_tampering_section(html: &mut String, score: &UnifiedScore) {
    let tamp = &score.forensic_report.tampering;

    let risk_class = if tamp.risk_score >= 0.5 {
        "high"
    } else if tamp.risk_score >= 0.2 {
        "medium"
    } else {
        "low"
    };

    html.push_str("<section>\n<h2>Tampering Analysis</h2>\n");
    html.push_str(&format!(
        "<div class=\"confidence {risk_class}\">\n\
         <span class=\"label\">Risk Score</span>\n\
         <span class=\"value\">{:.0}%</span>\n\
         </div>\n",
        tamp.risk_score * 100.0
    ));

    if !tamp.findings.is_empty() {
        html.push_str("<table>\n<tr><th>Severity</th><th>Category</th><th>Description</th></tr>\n");
        for f in &tamp.findings {
            html.push_str(&format!(
                "<tr class=\"{}\"><td>{:?}</td><td>{:?}</td><td>{}</td></tr>\n",
                match f.severity {
                    crate::forensics::tampering::Severity::High => "warning",
                    crate::forensics::tampering::Severity::Medium => "caution",
                    _ => "",
                },
                f.severity, f.category, escape(&f.description)
            ));
        }
        html.push_str("</table>\n");
    }

    if let Some(ref fp) = tamp.tool_fingerprint {
        html.push_str(&format!("<p>Tool: <strong>{}</strong>", escape(&fp.tool_name)));
        if let Some(ref v) = fp.tool_version {
            html.push_str(&format!(" v{v}"));
        }
        html.push_str("</p>\n");
    }

    html.push_str("</section>\n");
}

fn render_audit_section(html: &mut String, score: &UnifiedScore) {
    html.push_str("<section class=\"audit\">\n<h2>Audit Trail</h2>\n<table>\n");
    row(html, "Software", &format!("Provenance v{}", score.audit.software_version));
    row(html, "Timestamp", &score.audit.timestamp);
    row(html, "Input File", &score.audit.input_file_path);
    row(html, "File Hash", &score.audit.input_file_hash);
    row(html, "Config", &score.audit.config_summary);
    html.push_str("</table>\n</section>\n");
}

/// Render a table row.
fn row(html: &mut String, label: &str, value: &str) {
    html.push_str(&format!("<tr><td>{label}</td><td>{}</td></tr>\n", escape(value)));
}

/// HTML-escape a string.
fn escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

const CSS: &str = r#"
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
       max-width: 900px; margin: 0 auto; padding: 2rem; background: #fafafa; color: #222; }
header { text-align: center; margin-bottom: 2rem; border-bottom: 2px solid #333; padding-bottom: 1rem; }
h1 { font-size: 2rem; letter-spacing: 0.15em; text-transform: uppercase; }
.subtitle { color: #666; font-style: italic; }
h2 { font-size: 1.1rem; margin: 1.5rem 0 0.5rem; color: #444;
     border-left: 4px solid #2196F3; padding-left: 0.5rem; }
section { background: #fff; border: 1px solid #ddd; border-radius: 4px;
          padding: 1rem; margin-bottom: 1rem; }
table { width: 100%; border-collapse: collapse; font-size: 0.9rem; }
td, th { padding: 0.35rem 0.5rem; border-bottom: 1px solid #eee; text-align: left; }
th { background: #f5f5f5; font-weight: 600; }
tr:last-child td { border-bottom: none; }
td:first-child { font-weight: 500; color: #555; white-space: nowrap; width: 40%; }
code { background: #f0f0f0; padding: 0.15rem 0.3rem; border-radius: 3px; font-size: 0.85rem; }
.bar { background: #2196F3; height: 14px; border-radius: 2px; min-width: 2px; }
.confidence { display: flex; align-items: center; gap: 1rem; padding: 0.75rem;
              border-radius: 4px; margin-bottom: 0.75rem; }
.confidence .label { flex: 1; font-weight: 500; }
.confidence .value { font-size: 1.5rem; font-weight: 700; }
.confidence .level { font-size: 0.8rem; text-transform: uppercase; }
.confidence.high { background: #e8f5e9; border: 1px solid #4caf50; }
.confidence.medium { background: #fff3e0; border: 1px solid #ff9800; }
.confidence.low { background: #ffebee; border: 1px solid #f44336; }
.warning td { background: #fff3e0; color: #e65100; }
.caution td { background: #fffde7; }
.audit { opacity: 0.8; font-size: 0.85rem; }
footer { text-align: center; color: #999; font-size: 0.8rem; margin-top: 2rem;
         border-top: 1px solid #ddd; padding-top: 1rem; }
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_escape() {
        assert_eq!(escape("<b>test</b>"), "&lt;b&gt;test&lt;/b&gt;");
        assert_eq!(escape("a & b"), "a &amp; b");
    }
}
