//! Natural language explanation engine for AI detection results.
//!
//! Every score must be explainable with language suitable for non-technical users
//! (professors, editors, lawyers). This module transforms feature scores into
//! human-readable narratives explaining WHY a particular classification was reached.

use serde::{Deserialize, Serialize};

use super::scoring::{DetectionScore, DetectionTier, FeatureScore};
use super::countermeasures::CountermeasureReport;

/// Complete explanation of an AI detection result.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DetectionExplanation {
    /// One-paragraph executive summary suitable for non-technical readers.
    pub summary: String,
    /// Per-feature explanations in plain language, ordered by contribution.
    pub feature_explanations: Vec<FeatureNarrative>,
    /// Caveats and limitations for this specific analysis.
    pub caveats: Vec<String>,
    /// Countermeasure explanations (if any adjustments were applied).
    pub adjustment_explanations: Vec<String>,
}

/// Plain-language explanation of a single feature's contribution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeatureNarrative {
    /// Feature name.
    pub feature: String,
    /// Direction: does this feature push toward AI or human?
    pub direction: String,
    /// Magnitude: how much does this feature contribute?
    pub strength: ExplanationStrength,
    /// The narrative explanation.
    pub narrative: String,
}

/// Strength of a feature's contribution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ExplanationStrength {
    Strong,
    Moderate,
    Weak,
}

impl ExplanationStrength {
    pub fn label(&self) -> &'static str {
        match self {
            ExplanationStrength::Strong => "strong",
            ExplanationStrength::Moderate => "moderate",
            ExplanationStrength::Weak => "weak",
        }
    }
}

/// Generate a complete explanation for a detection result.
pub fn explain(
    score: &DetectionScore,
    countermeasures: &CountermeasureReport,
    word_count: usize,
) -> DetectionExplanation {
    let summary = generate_summary(score, countermeasures, word_count);
    let feature_explanations = generate_feature_narratives(&score.feature_scores);
    let caveats = generate_caveats(score, word_count);
    let adjustment_explanations = generate_adjustment_explanations(countermeasures);

    DetectionExplanation {
        summary,
        feature_explanations,
        caveats,
        adjustment_explanations,
    }
}

/// Generate the executive summary paragraph.
fn generate_summary(
    score: &DetectionScore,
    countermeasures: &CountermeasureReport,
    word_count: usize,
) -> String {
    let tier_desc = match score.tier {
        DetectionTier::HumanAuthored => {
            "The statistical indicators in this text are consistent with human authorship. \
             The writing shows natural patterns of word usage variation, sentence rhythm, \
             and linguistic complexity that are characteristic of human-written text."
        }
        DetectionTier::LikelyHuman => {
            "This text shows predominantly human writing patterns, with minor indicators \
             that could suggest some AI assistance or tool-aided editing. The overall \
             statistical profile is within the range typically seen in human-authored work."
        }
        DetectionTier::MixedUncertain => {
            "This text shows a mix of human and AI-associated patterns. The statistical \
             indicators are inconclusive — some features suggest human authorship while \
             others show patterns more commonly associated with AI-generated text. \
             Human review is recommended before drawing conclusions."
        }
        DetectionTier::AiAssisted => {
            "Several statistical indicators in this text are consistent with AI-assisted \
             writing. The patterns of word distribution, sentence structure, and linguistic \
             variation suggest that AI tools may have been used in the creation of this text. \
             Further investigation is recommended."
        }
        DetectionTier::AiGenerated => {
            "Multiple statistical indicators strongly suggest this text was generated by AI. \
             The patterns of word usage uniformity, sentence rhythm regularity, and reduced \
             linguistic variation are significantly outside the range of typical human writing."
        }
    };

    let mut summary = format!(
        "Analysis of {} words classified as {} ({}).\n\n{}",
        word_count, score.register_label, score.tier_label, tier_desc
    );

    // Add adjustment context
    let total_adjustment = countermeasures.total_adjustment();
    if total_adjustment.abs() > f64::EPSILON {
        summary.push_str(&format!(
            "\n\nNote: The score was adjusted by {:.2} based on detected text characteristics: {}.",
            total_adjustment,
            countermeasures.adjustment_summary()
        ));
    }

    if score.features_used < 5 {
        summary.push_str(
            "\n\nCaution: Fewer than 5 of 7 detection features could be computed for this text. \
             The confidence in this result is reduced."
        );
    }

    summary
}

/// Generate per-feature plain-language narratives.
fn generate_feature_narratives(features: &[FeatureScore]) -> Vec<FeatureNarrative> {
    let mut sorted = features.to_vec();
    sorted.sort_by(|a, b| {
        b.weighted_contribution
            .abs()
            .partial_cmp(&a.weighted_contribution.abs())
            .unwrap_or(std::cmp::Ordering::Equal)
    });

    sorted
        .iter()
        .map(|f| {
            let strength = if f.weighted_contribution.abs() > 0.10 {
                ExplanationStrength::Strong
            } else if f.weighted_contribution.abs() > 0.05 {
                ExplanationStrength::Moderate
            } else {
                ExplanationStrength::Weak
            };

            let direction = if f.normalized_score > 0.5 {
                "AI-associated".to_string()
            } else {
                "human-associated".to_string()
            };

            let narrative = generate_feature_narrative(&f.name, f.raw_value, f.normalized_score);

            FeatureNarrative {
                feature: f.name.clone(),
                direction,
                strength,
                narrative,
            }
        })
        .collect()
}

/// Generate a narrative for a specific feature.
fn generate_feature_narrative(name: &str, raw: f64, normalized: f64) -> String {
    match name {
        n if n.contains("Burstiness") => {
            if normalized > 0.5 {
                format!(
                    "This text shows unusually uniform word distribution (burstiness: {:.3}). \
                     Human writers typically cluster specific words in relevant sections, creating \
                     'bursty' usage patterns. This text distributes vocabulary more evenly, which \
                     is {:.0}x more consistent with AI-generated text.",
                    raw,
                    (normalized / 0.5).min(5.0)
                )
            } else {
                format!(
                    "Word usage in this text shows natural 'burstiness' ({:.3}), where specific \
                     words cluster in relevant sections rather than being distributed uniformly. \
                     This pattern is consistent with human writing.",
                    raw
                )
            }
        }
        n if n.contains("Zipf") => {
            if normalized > 0.5 {
                format!(
                    "The word frequency distribution follows Zipf's law very closely \
                     (deviation: {:.4}). AI models tend to produce text that adheres more \
                     tightly to statistical language laws, while human writing typically \
                     deviates more due to individual word preferences and topic-specific vocabulary.",
                    raw
                )
            } else {
                format!(
                    "The word frequency distribution deviates naturally from Zipf's law ({:.4}), \
                     showing the kind of individual vocabulary preferences typical of human writers.",
                    raw
                )
            }
        }
        n if n.contains("Hedge") => {
            if normalized > 0.5 {
                format!(
                    "The ratio of hedging language to intensifiers ({:.2}) is lower than typical \
                     human writing. Human authors tend to hedge more (\"perhaps\", \"might\", \
                     \"somewhat\") relative to their use of intensifiers (\"very\", \"extremely\"). \
                     AI text tends to over-use intensifiers and under-use hedges.",
                    raw
                )
            } else {
                format!(
                    "The balance between hedging and intensifying language ({:.2}) is within \
                     the range typical of human writers, who naturally hedge more than they intensify.",
                    raw
                )
            }
        }
        n if n.contains("autocorrelation") => {
            if normalized > 0.5 {
                format!(
                    "Consecutive sentence lengths are more correlated than typical human writing \
                     (autocorrelation: {:.4}). Human writers naturally vary their sentence rhythm \
                     more randomly, while AI tends to produce more rhythmically predictable text.",
                    raw
                )
            } else {
                format!(
                    "Sentence length variation shows natural randomness (autocorrelation: {:.4}), \
                     consistent with the unpredictable rhythm of human writing.",
                    raw
                )
            }
        }
        n if n.contains("POS") => {
            if normalized > 0.5 {
                format!(
                    "Syntactic variety is lower than typical human writing ({:.2} bits entropy). \
                     Human writers naturally produce more varied grammatical patterns. \
                     The repetitive syntactic structure in this text is more consistent with \
                     AI-generated content.",
                    raw
                )
            } else {
                format!(
                    "The text shows high syntactic variety ({:.2} bits), with diverse grammatical \
                     patterns consistent with human writing.",
                    raw
                )
            }
        }
        n if n.contains("diversity") => {
            if normalized > 0.5 {
                format!(
                    "Lexical diversity and sentence length are unusually correlated ({:.3}). \
                     In human writing, vocabulary richness and sentence length vary independently. \
                     AI text often couples these dimensions.",
                    raw
                )
            } else {
                format!(
                    "Vocabulary richness and sentence length vary independently ({:.3}), \
                     as expected in human writing.",
                    raw
                )
            }
        }
        n if n.contains("repetition") => {
            if normalized > 0.5 {
                format!(
                    "Content word repetition is unusually uniform across the text (delta: {:.3}). \
                     Human writers typically show more variation in how they reuse words between \
                     the first and second halves of their writing.",
                    raw
                )
            } else {
                format!(
                    "Content word reuse patterns vary naturally between sections ({:.3}), \
                     consistent with human writing.",
                    raw
                )
            }
        }
        _ => format!(
            "{}: raw value {:.3}, normalized score {:.3}",
            name, raw, normalized
        ),
    }
}

/// Generate caveats specific to this analysis.
fn generate_caveats(score: &DetectionScore, word_count: usize) -> Vec<String> {
    let mut caveats = Vec::new();

    caveats.push(
        "These results are statistical indicators, not definitive proof of AI or human \
         authorship. They should be considered alongside other evidence and human judgment."
            .to_string(),
    );

    if word_count < 1000 {
        caveats.push(format!(
            "This text is relatively short ({} words). Detection accuracy improves \
             significantly with texts over 1,000 words.",
            word_count
        ));
    }

    if score.features_used < 5 {
        caveats.push(format!(
            "Only {} of 7 detection features could be computed. Results with fewer than \
             5 features should be treated with additional caution.",
            score.features_used
        ));
    }

    if score.register_adjustment.abs() > 0.10 {
        caveats.push(format!(
            "A register adjustment of {:+.2} was applied because this text was classified \
             as {}. Certain text types (legal, academic, technical) naturally exhibit \
             patterns that overlap with AI indicators.",
            score.register_adjustment, score.register_label
        ));
    }

    if score.adjusted_score > 0.35 && score.adjusted_score < 0.65 {
        caveats.push(
            "This text falls in the uncertain range. Mixed/uncertain results are common \
             for texts that were human-written with AI editing assistance, or for non-native \
             English speakers. Human review is strongly recommended."
                .to_string(),
        );
    }

    caveats
}

/// Generate explanations for any countermeasure adjustments.
fn generate_adjustment_explanations(countermeasures: &CountermeasureReport) -> Vec<String> {
    let mut explanations = Vec::new();

    if countermeasures.nnes_adjustment.abs() > f64::EPSILON {
        explanations.push(format!(
            "Non-native English speaker patterns detected (confidence: {:.0}%). Score \
             adjusted by {:.2} to reduce false positive risk. NNES writers naturally produce \
             text with lower burstiness and more formulaic patterns that can mimic AI indicators.",
            countermeasures.nnes_confidence * 100.0,
            countermeasures.nnes_adjustment
        ));
    }

    if countermeasures.template_adjustment.abs() > f64::EPSILON {
        explanations.push(format!(
            "Template/boilerplate content detected ({:.0}% of text). Only non-template \
             sections were scored. Template content (legal boilerplate, academic headers, \
             disclaimers) naturally exhibits low variation.",
            countermeasures.template_fraction * 100.0
        ));
    }

    if countermeasures.editing_tool_adjustment.abs() > f64::EPSILON {
        explanations.push(format!(
            "Editing tool patterns detected (confidence: {:.0}%). Score adjusted by {:.2}. \
             Tools like Grammarly and ProWritingAid normalize sentence structure and reduce \
             natural variation, creating patterns that overlap with AI indicators.",
            countermeasures.editing_tool_confidence * 100.0,
            countermeasures.editing_tool_adjustment
        ));
    }

    if countermeasures.humanizer_adjustment > f64::EPSILON {
        explanations.push(format!(
            "Humanizer tool artifacts detected (confidence: {:.0}%). Score increased by \
             +{:.2}. Humanizer tools (Undetectable.ai, QuillBot, etc.) modify AI-generated \
             text to evade detection, leaving characteristic statistical fingerprints.",
            countermeasures.humanizer_confidence * 100.0,
            countermeasures.humanizer_adjustment
        ));
    }

    explanations
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::detection::scoring::DetectionTier;

    fn make_score(tier: DetectionTier, adjusted: f64, features_used: usize) -> DetectionScore {
        DetectionScore {
            score: adjusted,
            adjusted_score: adjusted,
            tier,
            tier_label: tier.label().to_string(),
            action: tier.action().to_string(),
            register_adjustment: 0.0,
            register_label: "Casual / Blog Post".to_string(),
            features_used,
            feature_scores: Vec::new(),
            confidence: features_used as f64 / 7.0,
        }
    }

    #[test]
    fn test_human_summary() {
        let score = make_score(DetectionTier::HumanAuthored, 0.10, 7);
        let cm = CountermeasureReport::default();
        let explanation = explain(&score, &cm, 2000);
        assert!(explanation.summary.contains("human authorship"));
    }

    #[test]
    fn test_low_feature_caveat() {
        let score = make_score(DetectionTier::MixedUncertain, 0.50, 3);
        let cm = CountermeasureReport::default();
        let explanation = explain(&score, &cm, 600);
        assert!(explanation.caveats.iter().any(|c| c.contains("3 of 7")));
    }

    #[test]
    fn test_nnes_adjustment_explanation() {
        let score = make_score(DetectionTier::LikelyHuman, 0.30, 7);
        let cm = CountermeasureReport {
            nnes_adjustment: -0.15,
            nnes_confidence: 0.6,
            ..Default::default()
        };
        let explanation = explain(&score, &cm, 1500);
        assert!(explanation.adjustment_explanations.iter().any(|e| e.contains("Non-native")));
    }
}
